env="DoorKey-8x8"
int_rew_source="AEGIS"
seed=0
pretrain_percentage=0.0
total_steps=500_000
int_rew_momentum=0.9
rnd_err_norm=1
int_rew_coef=1e-2

# PYTHONPATH=./ python3 src/train.py \
#           --run_id=$seed \
#           --total_steps=$total_steps \
#           --pretrain_percentage=$pretrain_percentage \
#           --int_rew_source=$int_rew_source \
#           --env_source=minigrid \
#           --game_name=$env \
#           --num_processes=16 \
#           --n_steps=512 \
#           --batch_size=512 \
#           --n_epochs=1 \
#           --model_n_epochs=1 \
#           --features_dim=64 \
#           --model_features_dim=64 \
#           --latents_dim=128 \
#           --model_latents_dim=128 \
#           --int_rew_coef=$int_rew_coef \
#           --int_rew_momentum=$int_rew_momentum \
#           --rnd_err_norm=$rnd_err_norm

env="jumper"
PYTHONPATH=./ python3 src/train.py \
        --run_id=$seed \
        --total_steps=$total_steps \
        --pretrain_percentage=$pretrain_percentage \
        --int_rew_source=$int_rew_source \
        --env_source=procgen \
        --game_name=$env \
        --num_processes=64 \
        --n_steps=256 \
        --batch_size=2048 \
        --n_epochs=1 \
        --model_n_epochs=1 \
        --learning_rate=1e-4 \
        --model_learning_rate=1e-4 \
        --features_dim=256 \
        --model_features_dim=256 \
        --policy_cnn_type=2 \
        --policy_cnn_norm=LayerNorm \
        --policy_mlp_norm=NoNorm \
        --model_cnn_type=1 \
        --model_cnn_norm=LayerNorm \
        --model_mlp_norm=NoNorm \
        --adv_norm=0 \
        --int_rew_coef=$int_rew_coef \
        --int_rew_momentum=$int_rew_momentum \
        --rnd_err_norm=$rnd_err_norm